Homebrew: remove upgrade cleanup env var
Homebrew 2.0 does some cleanup automatically and running `brew upgrade`
fails when this option is set.

> Error: Calling 'HOMEBREW_UPGRADE_CLEANUP' is disabled! There is no
> replacement.